version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    environment:
      GRAPHQL_URL: ${GRAPHQL_URL}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - .env:/app/.env
    restart: always
    ports:
      - 3000:3000
